import React from 'react';
import { Metadata } from 'next';
import { constructMetadata } from '@/lib/metadata';
import { Container } from '@/components/ui/Container';
import { Section } from '@/components/ui/Section';
import { PageHeader } from '@/components/ui/PageHeader';
import { FAQ, FAQItem } from '@/components/ui/FAQ';
import { AdPlaceholder } from '@/components/ui/AdPlaceholder';
import { TranscriptionWorkspace } from '@/components/tools/TranscriptionWorkspace';
import { JsonLd } from '@/components/JsonLd';
import { siteConfig } from '@/config/site';

export const metadata: Metadata = constructMetadata({
  title: 'Audio to Text with Timestamps | Konthora',
  description:
    'Transcribe audio or video into accurate text with sentence, paragraph or word timestamps. Export transcripts as TXT, SRT, VTT or JSON.',
  path: '/audio-to-text',
});

export default function AudioToTextPage() {
  const pageUrl = `${siteConfig.url}/audio-to-text`;

  // Structured Data (JSON-LD)
  const webAppSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Konthora Audio to Text with Timestamps',
    url: pageUrl,
    applicationCategory: 'MultimediaApplication',
    operatingSystem: 'All',
    browserRequirements: 'Requires a modern web browser with HTML5 support.',
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: siteConfig.url,
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Audio to Text',
        item: pageUrl,
      },
    ],
  };

  const audioFaqs: FAQItem[] = [
    {
      question: 'What is the maximum upload file size?',
      answer:
        'The maximum file size per upload is 100 MB. For longer recordings, files must also be within a 10-minute duration limit.',
    },
    {
      question: 'Which file formats are supported for transcription?',
      answer:
        'Konthora accepts MP3, WAV, M4A, AAC, MP4, WebM, and MOV files. Video files are processed for their audio track only.',
    },
    {
      question: 'Which languages are supported?',
      answer:
        'Konthora currently transcribes English-language audio. Selecting "Auto Detect" will also process the audio as English. Additional language support is planned for a future release.',
    },
    {
      question: 'How accurate are the timestamps?',
      answer:
        'Timestamps are generated by Whisper, a production-grade speech recognition model. You can choose sentence-level, paragraph-level, or word-level timestamp grouping for your use case.',
    },
    {
      question: 'What export formats are available?',
      answer:
        'You can export your transcript as plain TXT, SRT subtitle format, WebVTT caption format, or structured JSON containing all segments and word-level timing data.',
    },
    {
      question: 'Are uploaded files stored permanently?',
      answer:
        'No. Uploaded media files and generated transcripts are automatically deleted after 60 minutes. Nothing is retained beyond that window.',
    },
  ];

  return (
    <>
      <JsonLd schema={webAppSchema} />
      <JsonLd schema={breadcrumbSchema} />

      <Section className="pb-6">
        <Container>
          <PageHeader
            title="Audio to Text with Timestamps"
            description="Upload an audio or video file and receive an accurate, timestamped transcript. Choose sentence, paragraph, or word-level grouping and export as TXT, SRT, VTT, or JSON."
            badge="Transcription"
          />
          <TranscriptionWorkspace />
          <AdPlaceholder />
        </Container>
      </Section>

      {/* Tool FAQ Section */}
      <Section className="bg-secondary/10">
        <Container>
          <div className="text-center mb-12">
            <h2 className="text-2xl font-bold text-foreground">
              Transcription FAQs
            </h2>
            <p className="mt-2 text-muted-foreground">
              Common questions about Konthora&apos;s audio transcription tool.
            </p>
          </div>
          <FAQ items={audioFaqs} />
        </Container>
      </Section>
    </>
  );
}
